# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

r_github_packages:
  - petermeissner/stringb
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

