# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to check which chars belong to which token
#' takes a vector of xs to check if these lie between pairs of ys and if so
#' returning their index; assumes xs and ys are sorted; returns only the first
#' span index which enclosing the x
#' @param x whatever
#' @param y1 whatever
#' @param y2 whatever
which_token_worker <- function(x, y1, y2) {
    .Call('rtext_which_token_worker', PACKAGE = 'rtext', x, y1, y2)
}

